---
title: "Superstore Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DT)
library(plotly)
library(dplyr)
df = read.csv("./superstore.csv")
state_codes = read.csv("https://raw.githubusercontent.com/plotly/datasets/master/2011_us_ag_exports.csv")[,1:2]
```

USA : Business Analysis
================================================================================
```{r eruptions, echo=FALSE}
inputPanel(
  selectInput("cat", label = "Category:",
              choices = unique(df$Category), selected = "Office Supplies"),
  selectInput("typ", label = "Type:",
              choices = c("Sales", "Discount", "Profit"), selected = "Profit")

#  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
#              min = 0.2, max = 2, value = 1, step = 0.2)
)

renderPlotly({
  df_cat = df %>% filter(Category == input$cat)
  df_cat = aggregate(df_cat[, 18:21], list(df_cat$State), mean)
  df_cat = merge(x=df_cat, y=state_codes, by.x= "Group.1", by.y = "state")
  df_cat$hover <- with(df_cat, paste(Group.1, "<br>Sales: ", round(Sales, digits = 2),
                                     "<br>Discount: ", round(Discount, digits = 2),
                                     "<br>Profits: ", round(Profit, digits = 2)
                                     ))
  l <- list(color = toRGB("white"), width = 2)
  g <- list(
    scope = 'usa',
    projection = list(type = 'albers usa')
  )
  fig <- plot_ly(type="choropleth", locations=df_cat$code,
                 locationmode="USA-states", text = df_cat$hover,
                 z=df_cat[, c(input$typ)]) %>% layout(geo=g)
  fig <- fig %>% colorbar(title ="in USD")
  fig <- fig %>% layout(
    title = paste("Average", input$typ, "in", input$cat)
  )
  fig
})
```



Volume Divisions
================================================================================
```{r, echo=FALSE}
inputPanel(
  selectInput("typ2", label = "Type:",
              choices = c("Ship.Mode", "Segment"), selected = "Ship.Mode")
)
renderPlotly({
  ship_mode_freq = data.frame(table(df[,c(input$typ2)]))
  fig <- plot_ly(ship_mode_freq, labels = ~Var1, values = ~Freq, type= "pie", textinfo='label+percent')
  # fig <- fig %>% add_pie(hole = 0.6)
  fig <- fig %>% layout(title = paste(input$typ2, 'of People'),
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
  fig
  })
```


Business Trinity
================================================================================
```{r, echo=FALSE}
df<- read.csv("./superstore.csv")
fig <- plot_ly(df[seq(1,50000,500),], x = ~df$Sales, y = ~df$Profit, z = ~df$Discount,
               marker = list(color = ~df$Quantity, colorscale = c('#FFE1A1', '#683531'), showscale = TRUE))
fig <- fig %>% add_markers()
fig <- fig %>% layout(scene = list(xaxis = list(title = 'Quantity'),
                                   yaxis = list(title = 'Sales'),
                                   zaxis = list(title = 'Profit')),
                      annotations = list(
                        x = 1,
                        y = 1,
                        text = 'Profits',
                        xref = 'paper',
                        yref = 'paper',
                        showarrow = FALSE
                      ),paper_bgcolor = '#FFFFFF',
                      plot_bgcolor = '#000000',
                      font = list(color = "#000000"))
fig
```


Shipment Trends
================================================================================
```{r,echo =FALSE}
df%>%
  group_by(Sub.Category)%>%
  ggplot(aes(Sub.Category,fill=Ship.Mode))+
  geom_bar(position = 'fill')+
  scale_fill_manual(values = c("#DADAEB", "#9E9AC8", "#6A51A3","#301934"))+
  coord_flip()+
  labs(title='There is no prefered ship mode in different products',
       x='Proportion',
       y='Sub Category')+
  theme_bw()+
  theme(plot.margin = unit(c(3,1,1,1), "cm"))
```

Trend of Sale and Profits
================================================================================
<br />
```{r, echo=FALSE}
suppressPlotlyMessage <- function(p) {
  suppressMessages(plotly_build(p))
}

fig <- suppressPlotlyMessage(plot_ly(data = df[seq(1,5000,50),], x = ~Sales, y = ~Profit,
               marker = list(size = 6,
                             color = 'rgba(255, 182, 193, .9)',
                             line = list(color = 'rgba(152, 0, 0, .8)',
                                         width = 1))))
fig <- fig %>% layout(title = 'Sales vs Profit',
         yaxis = list(zeroline = FALSE),
         xaxis = list(zeroline = FALSE),
         margin = c(t=100))

fig
```


Top Cities
================================================================================

Visualization {data-width=800}
--------------------------------------------------------------------------------

```{r, echo=FALSE}
renderPlotly({

  df_city_agg = aggregate(df[, c(input$typ3)], list(df$City), sum)
  df_top5 = head(df_city_agg[order(df_city_agg$x, decreasing = TRUE),], n=input$bw_adjust)

x <- df_top5$Group.1
y <- df_top5$x
text <- df_top5$Group.1
data <- data.frame(x, y, text)

fig <- plot_ly(data, x = ~x, y = ~y, type = 'bar', text = text,
        marker = list(color = 'rgb(235, 190, 209)',
                      line = list(color = 'rgb(232, 76, 134)',
                                  width = 1.5)))
fig <- fig %>% layout(title = paste("Top",input$bw_adjust,"Cities in", input$typ3),
         xaxis = list(title = ""),
         yaxis = list(title = ""),
         margin = c(t=100),
         height = 700)

fig
})
```


Control Panel{data-width=100}
--------------------------------------------------------------------------------
```{r, echo=FALSE}
inputPanel(
  selectInput("typ3", label = "Type:",
              choices = c("Sales", "Discount", "Profit"), selected = "Profit"),
  sliderInput("bw_adjust", label = "No. of cities:",
              min = 2, max = 10, value = 5, step = 1)
)
```

Shipping Time Analysis
================================================================================


Average Shipping Time per city
--------------------------------------------------------------------------------
```{r, echo=FALSE}

state_wise_sales_average = tapply(df$Sales, df$State, mean)
df$shipping_time <-  as.Date(as.character(df$Ship.Date), format="%m/%d/%Y") - as.Date(as.character(df$Order.Date), format="%m/%d/%Y")
average_shipping_time_by_province = data.frame(tapply(df$shipping_time, df$State, mean))
average_shipping_time_by_province$state = rownames(average_shipping_time_by_province)
dff2 = merge(x=average_shipping_time_by_province, y=state_codes, by.x= "state", by.y = "state")
colnames(dff2) = c('state','avgst','code')
dff2$hover <- with(dff2, paste(state, "<br>Days: ", round(avgst, digits = 1)))

# give state boundaries a white border
l <- list(color = toRGB("white"), width = 2)
# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa')
)

fig <- plot_ly(type="choropleth", locations=dff2$code,
               locationmode="USA-states",
               text = dff2$hover,
               z=dff2$avgst) %>% layout(geo=g)
fig <- fig %>% colorbar(title = "Days")
fig <- fig %>% layout(
  title = 'Average Shipping Time'
)

fig


```

Average Shipping Time by Shipping Mode
--------------------------------------------------------------------------------
```{r, echo=FALSE}

average_shipping_time_by_mode_of_transport = data.frame(tapply(df$shipping_time, df$Ship.Mode, mean))
average_shipping_time_by_mode_of_transport$class = rownames(average_shipping_time_by_mode_of_transport)

colnames(average_shipping_time_by_mode_of_transport) = c('timeavg', 'class')

x <- average_shipping_time_by_mode_of_transport$class
y <- average_shipping_time_by_mode_of_transport$timeavg
text <- ""
data <- data.frame(x, y, text)

fig <- plot_ly(data = data, x= ~x, y= ~y,  type = 'bar', text = text,
               marker = list(color = 'rgb(235, 190, 209)',
                             line = list(color = 'rgb(232, 76, 134)',
                                         width = 1.5)))
fig <- fig %>% layout(title = "Average Shipping Time by Mode of Transport",
                      xaxis = list(title = ""),
                      yaxis = list(title = ""))

fig

```

Heatmap
================================================================================
```{r, echo=FALSE}
inputPanel(
  selectInput("typ4", label = "Type:",
              choices = c("Sales", "Profit"), selected = "Sales"),
)
renderPlot({
df%>%
  group_by(Sub.Category, Segment)%>%
  summarise(n=sum(if (input$typ4 == "Sales") Sales else Profit))%>%
  ggplot(aes(Segment, Sub.Category, fill=n))+
  scale_fill_distiller(palette = "GnBu", direction = 1)+
  geom_tile(color='white')+
  geom_text(aes(label=paste(round(n,0),'$')), color = 'black', size=3)+
  theme_bw()+
  labs(title=paste(input$typ4,': Segment vs. Sub-Category'),
       fill=input$typ4)
})
```

Discounts
================================================================================
```{r, echo=FALSE}
inputPanel(
  selectInput("cat2", label = "Category:",
              choices = unique(df$Category), selected = "Office Supplies")
)
renderPlot({
df<-df%>%mutate(Discount=cut_width(Discount,0.15,boundary=0))
df%>%
  filter(Category == input$cat2)%>%
  ggplot(aes(Sales, Profit, color=Discount))+
  geom_point()+
  theme_bw()+
  labs(title = paste(input$cat2, ': Sales vs Profits'), color='Discount')+
  facet_wrap(~Sub.Category)
})
```
